export const CATEGORIES = [
  { key: 'all', label: 'All' },
  { key: 'tee', label: 'Driving' },
  { key: 'fairway', label: 'Fairway' },
  { key: 'green_area', label: 'Chipping' },
  { key: 'on_green', label: 'Putting' },
  { key: 'trouble', label: 'Trouble' },
  { key: 'conditions', label: 'Conditions' },
  { key: 'equipment', label: 'Equipment' },
  { key: 'mental', label: 'Mental' },
  { key: 'distraction', label: 'Distraction' },
  { key: 'funny', label: 'Wild Cards' },
];

export const EXCUSES = [
  { text: "It was leg day today.", tags: ['conditions', 'funny'] },
  { text: "Barometric pressure must be dropping today.", tags: ['conditions'] },
  { text: "Back is tight, can't swing my normal swing.", tags: ['tee', 'fairway', 'conditions'] },
  { text: "It's a good bogey hole anyway.", tags: ['funny'] },
  { text: "I got two hours of sleep last night. Surprised I even found the course.", tags: ['conditions', 'mental'] },
  { text: "That guy three holes over was talking during my backswing.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "I got hit by a car on the way to the course.", tags: ['funny'] },
  { text: "Grabbed the wrong club.", tags: ['fairway', 'equipment'] },
  { text: "Someone hollered three holes over.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "The glare got me.", tags: ['conditions'] },
  { text: "You're standing too close.", tags: ['distraction'] },
  { text: "I heard you taking off your glove in my backswing.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "My golf coach has me working on something new.", tags: ['tee', 'fairway'] },
  { text: "I'm trying a new swing, still bedding it in.", tags: ['tee', 'fairway'] },
  { text: "The people in front are so slow, gets me out of my rhythm.", tags: ['distraction'] },
  { text: "I slipped.", tags: ['conditions'] },
  { text: "My underwear keeps riding up.", tags: ['funny'] },
  { text: "This jacket is too restrictive.", tags: ['tee', 'fairway', 'conditions'] },
  { text: "That squirrel was looking at me during my backswing.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "It was too hot, I got dehydrated and lost my focus.", tags: ['conditions'] },
  { text: "It was too cold, the ball wasn't going anywhere.", tags: ['conditions'] },
  { text: "I was so cold I could hardly swing the club.", tags: ['tee', 'fairway', 'conditions'] },
  { text: "The wind picked up right when I was over the ball.", tags: ['conditions'] },
  { text: "I'm still searching for a ball that goes straight.", tags: ['tee', 'fairway', 'equipment'] },
  { text: "With my defective balls, a perfect shot ends up in the woods for no reason.", tags: ['tee', 'trouble', 'equipment'] },
  { text: "My clubs are all mismatched and old, I'd play better with new ones.", tags: ['tee', 'fairway', 'equipment'] },
  { text: "The course was so wet nothing was rolling.", tags: ['conditions'] },
  { text: "Uneven greens, I couldn't trust a single putt.", tags: ['on_green', 'conditions'] },
  { text: "A squirrel was chewing a nut in a tree two fairways away, threw me off.", tags: ['distraction'] },
  { text: "Perfect shot, then it rolled back into the bunker, some days you can't buy a shot.", tags: ['green_area', 'funny'] },
  { text: "Great drive, then an unlucky bounce and a 90 degree turn into the hazard.", tags: ['tee', 'trouble', 'funny'] },
  { text: "The bounces just weren't going my way today.", tags: ['conditions', 'funny'] },
  { text: "Inconsistent swing is the trademark of my game.", tags: ['tee', 'fairway'] },
  { text: "I'm not sure if I was fly fishing or golfing out there.", tags: ['tee', 'fairway'] },
  { text: "I looked like I got kicked by a horse and then stung by a bee during my swing.", tags: ['tee', 'fairway'] },
  { text: "I stood over the putt thinking \"What am I lying?\" instead of making the putt.", tags: ['on_green', 'mental'] },
  { text: "I score lower when I play alone, no distractions today.", tags: ['mental'] },
  { text: "I flew in five minutes before tee time, no warm up.", tags: ['mental'] },
  { text: "You had an hour of range and putting, I had five minutes. Life isn't fair.", tags: ['mental'] },
  { text: "It's not like I'm going to lose my Tour card, but still.", tags: ['funny'] },
  { text: "I hit my 150 yard club and came up 20 yards short, the 150 marker's in the wrong place.", tags: ['fairway', 'equipment'] },
  { text: "The sun was in my eyes.", tags: ['conditions'] },
  { text: "Someone coughed during my backswing.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "The grass was the wrong length.", tags: ['fairway', 'conditions'] },
  { text: "My glove was too tight.", tags: ['tee', 'fairway', 'equipment'] },
  { text: "A bug flew right in my face mid-swing. What am I supposed to do?", tags: ['tee', 'fairway', 'distraction'] },
  { text: "The wind changed mid swing.", tags: ['tee', 'fairway', 'conditions'] },
  { text: "Wrong ball, I thought it was mine.", tags: ['fairway', 'equipment'] },
  { text: "Cart path only, threw off my routine.", tags: ['conditions', 'mental'] },
  { text: "Was this out of bounds last week?", tags: ['trouble', 'funny'] },
  { text: "My tee had a crack in it.", tags: ['tee', 'equipment'] },
  { text: "I putted great at miniature golf yesterday.", tags: ['on_green', 'funny'] },
  { text: "I can't focus, my cell phone is dead.", tags: ['distraction'] },
  { text: "I felt whiplash when you started the cart.", tags: ['distraction'] },
  { text: "I just love these new clubs!", tags: ['tee', 'fairway', 'equipment'] },
  { text: "Those 3 footers throw me off.", tags: ['on_green', 'mental'] },
  { text: "That darn sprinkler head got in my way.", tags: ['fairway', 'conditions'] },
  { text: "Why am I hitting straight? I usually slice.", tags: ['tee', 'fairway'] },
  { text: "I had my tee too low.", tags: ['tee'] },
  { text: "I had my tee too high.", tags: ['tee'] },
  { text: "I'm afraid a snake might be in there!", tags: ['trouble', 'funny'] },
  { text: "I can't forget that triple bogey from last year.", tags: ['mental'] },
  { text: "I hate these new clubs!", tags: ['tee', 'fairway', 'equipment'] },
  { text: "It's too darn sunny out here.", tags: ['conditions'] },
  { text: "I play much better after a manicure.", tags: ['funny'] },
  { text: "That hole isn't regulation size!", tags: ['on_green', 'funny'] },
  { text: "My instructor said my biggest problem was standing too close\u2026 to the golf course.", tags: ['funny'] },
  { text: "This is gonna be one heck of a par.", tags: ['funny'] },
  { text: "Wind got ahold of that one.", tags: ['conditions'] },
  { text: "The wind was in my eyes.", tags: ['conditions', 'funny'] },
  { text: "Thinking about going pro, what do you guys think?", tags: ['funny'] },
  { text: "Ball must be cracked.", tags: ['tee', 'fairway', 'equipment'] },
  { text: "Swinging this golf club like a football bat today.", tags: ['tee', 'fairway'] },
  { text: "Failed to snap load my power package.", tags: ['tee', 'fairway'] },
  { text: "Can I pick up for a double from there?", tags: ['funny'] },
  { text: "Quit hitting the ball, instead swing the club!", tags: ['tee', 'fairway'] },
  { text: "I told Beyonc\u00e9 to not text me during my backswing!", tags: ['funny'] },
  { text: "Didn't account for the earth's rotation!", tags: ['funny'] },
  { text: "I think that was a left handed ball.", tags: ['funny'] },
  { text: "Forgot my swing at home.", tags: ['tee', 'fairway', 'mental'] },
  { text: "A noise from the gallery when I was taking my swing.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "Lifted my head, wins every time.", tags: ['tee', 'fairway'] },
  { text: "I'm too strong for this game.", tags: ['tee', 'fairway', 'funny'] },
  { text: "Tough break, I had a bad lie.", tags: ['fairway', 'conditions'] },
  { text: "The person two holes behind me rushed my shot, hit it out of bounds twice.", tags: ['trouble', 'distraction'] },
  { text: "I'm a carpet fitter, when I play after work I'm forever over hitting the ball.", tags: ['tee', 'fairway', 'funny'] },
  { text: "I've been using the kids' clubs in the backyard all week, threw off my swing.", tags: ['tee', 'fairway', 'equipment'] },
  { text: "Wind took it.", tags: ['tee', 'fairway', 'conditions'] },
  { text: "That was obviously the wrong club.", tags: ['fairway', 'equipment'] },
  { text: "Something made a noise while I was swinging, a car, a bird, a guy in a cart on the other hole.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "A sudden, unexpected gust of wind, did you feel that? Where did that come from?", tags: ['conditions'] },
  { text: "I knew I shouldn't have hit that driver. I hate that club.", tags: ['tee', 'equipment'] },
  { text: "Who had to plant a tree right there?", tags: ['trouble', 'funny'] },
  { text: "I hit it short, the yardage on this hole must be wrong.", tags: ['fairway', 'equipment'] },
  { text: "I hit it long, the yardage on this hole must be wrong.", tags: ['fairway', 'equipment'] },
  { text: "That putt broke way more than I expected.", tags: ['on_green'] },
  { text: "These greens are way too fast.", tags: ['on_green', 'conditions'] },
  { text: "These greens are way too bumpy. That should have gone in.", tags: ['on_green', 'conditions'] },
  { text: "Will you stop laughing? I can't concentrate.", tags: ['distraction'] },
  { text: "That shot rolled too far. Don't they water the fairways?", tags: ['fairway', 'conditions'] },
  { text: "That shot didn't roll at all. These fairways are too soft.", tags: ['fairway', 'conditions'] },
  { text: "The sun is too hot, my hands are sweaty and I can't hold the club.", tags: ['conditions'] },
  { text: "It's too cold, the club feels stiff and the ball feels like a rock.", tags: ['conditions'] },
  { text: "The group in front is too slow, all that waiting throws my game off.", tags: ['distraction'] },
  { text: "The group behind is too fast, them waiting on us throws my game off.", tags: ['distraction'] },
  { text: "An airplane flew over right during my downswing. How am I supposed to concentrate?", tags: ['tee', 'fairway', 'distraction'] },
  { text: "A bird dive-bombed right across my target line mid-swing.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "A horse and buggy rolled past the course. My focus was completely gone.", tags: ['distraction'] },
  { text: "Someone was smacking their gum so loud behind me I couldn't focus.", tags: ['distraction'] },
  { text: "The sheep see me coming, they BAAAAH in unison when I step up on #4.", tags: ['tee', 'distraction'] },
  { text: "Don't speak to my ball, you're making it go the wrong way.", tags: ['distraction'] },
  { text: "I swear the Golf Gods are real and they hate me.", tags: ['funny'] },
  { text: "Must be a defective golf ball, MGS said there are 2.64 bad balls per dozen.", tags: ['tee', 'fairway', 'equipment'] },
  { text: "I ate too much before the round. I'm so bloated I can't even rotate.", tags: ['conditions', 'funny'] },
  { text: "I have a hard time playing in this sun.", tags: ['conditions'] },
  { text: "This heat is unnatural. No one can play in this.", tags: ['conditions'] },
  { text: "That groundhog threw me off.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "My lumbago is acting up.", tags: ['conditions'] },
  { text: "I was hitting them so well at the range yesterday.", tags: ['tee', 'fairway', 'mental'] },
  { text: "I've been stuck in the office too much to hit the range.", tags: ['mental'] },
  { text: "I've played too much golf this week, the legs are dead.", tags: ['conditions'] },
  { text: "I hate the sand in these bunkers!", tags: ['green_area'] },
  { text: "Genes. I was born insufficiently talented.", tags: ['funny'] },
  { text: "Someone was narrating in my backswing.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "Somebody moved in my backswing.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "The wind didn't take my ball like it was supposed to.", tags: ['conditions'] },
  { text: "I swear, this is the worst round I've played in five years.", tags: ['mental'] },
  { text: "I had both knees replaced last winter.", tags: ['conditions'] },
  { text: "I'm testing this driver shaft.", tags: ['tee', 'equipment'] },

  // -- Around the Green --
  { text: "I skulled that chip because my hands were ahead. Wait, or behind?", tags: ['green_area', 'funny'] },
  { text: "The bunker sand was way too fluffy, impossible to get clean contact.", tags: ['green_area', 'conditions'] },
  { text: "I bladed it across the green because the lie was too perfect. Seriously.", tags: ['green_area', 'funny'] },
  { text: "Who puts a bunker right there? That's just cruel course design.", tags: ['green_area', 'funny'] },
  { text: "My wedge grooves are worn out, that's why the ball didn't check up.", tags: ['green_area', 'equipment'] },
  { text: "I left it in the bunker because I didn't want to fly the green.", tags: ['green_area', 'mental'] },
  { text: "That chip ran out because they didn't water the greens enough.", tags: ['green_area', 'conditions'] },
  { text: "I chunked it because there was too much dew on the grass.", tags: ['green_area', 'conditions'] },
  { text: "The fringe was cut against me, nothing I could do.", tags: ['green_area', 'conditions'] },
  { text: "That flop shot was perfect, the wind just carried it over the green.", tags: ['green_area', 'conditions'] },
  { text: "I was between clubs around the green and picked the wrong one. Classic.", tags: ['green_area', 'equipment'] },
  { text: "My sand wedge has a mind of its own today.", tags: ['green_area', 'equipment'] },
  { text: "I've been practicing my bump-and-run. It just didn't bump or run.", tags: ['green_area'] },
  { text: "That bunker lip was way higher than it looked from down there.", tags: ['green_area', 'funny'] },
  { text: "I thinned it because someone's shadow crossed my line.", tags: ['green_area', 'distraction'] },
  { text: "The ball was sitting down in the rough, no chance of a clean chip.", tags: ['green_area', 'conditions'] },
  { text: "I can't pitch when the pin is tucked that close to the edge.", tags: ['green_area', 'mental'] },
  { text: "Best two balls I hit all day was when I stepped on the bunker rake.", tags: ['green_area', 'funny'] },
  { text: "I moved everything but my bowels on that chip shot.", tags: ['green_area', 'funny'] },
  { text: "That bunker shot was so clean it deserved a tip jar. Too bad it went sideways.", tags: ['green_area'] },

  // -- On the Green --
  { text: "I read the putt perfectly. The green read it differently.", tags: ['on_green', 'mental'] },
  { text: "That putt was dead center. The hole just moved.", tags: ['on_green', 'funny'] },
  { text: "The ball mark I fixed changed the break completely.", tags: ['on_green', 'funny'] },
  { text: "I left it short because you should never charge a downhill putt.", tags: ['on_green', 'mental'] },
  { text: "These greens are running at least 14 on the stimp. Way too fast.", tags: ['on_green', 'conditions'] },
  { text: "My putter face was one degree open. That's all it takes.", tags: ['on_green', 'equipment'] },
  { text: "I decelerated through the ball. My sports psychologist is working on it.", tags: ['on_green', 'mental'] },
  { text: "Three putts happen. Four putts build character.", tags: ['on_green', 'funny'] },
  { text: "I can sink 30-footers all day but give me a 3-footer and I'm done.", tags: ['on_green', 'mental'] },
  { text: "The grain was going the other way. Nothing you can do.", tags: ['on_green', 'conditions'] },
  { text: "I had it on line, the spike marks knocked it off.", tags: ['on_green', 'conditions'] },
  { text: "My putting stroke is money on the practice green, but it disappears on the course.", tags: ['on_green', 'mental'] },
  { text: "I plumb-bobbed it and my plumb bob lied to me.", tags: ['on_green', 'equipment'] },
  { text: "That lip-out was personal. The hole rejected me.", tags: ['on_green', 'funny'] },
  { text: "It's not a miss, it's aggressive green reading.", tags: ['on_green', 'funny'] },
  { text: "Nice lag.", tags: ['on_green', 'funny'] },
  { text: "Why did I change putters right before the round? Why do I do this to myself?", tags: ['on_green', 'equipment'] },

  // -- Trouble --
  { text: "I aimed for the fairway and the ball aimed for the water.", tags: ['trouble', 'tee'] },
  { text: "That's not OB, that's just an alternative fairway.", tags: ['trouble', 'funny'] },
  { text: "I yelled fore but the ball didn't listen.", tags: ['trouble', 'tee'] },
  { text: "My ball found water on a hole with no water hazard. Impressive.", tags: ['trouble', 'funny'] },
  { text: "Lost ball? No, I know exactly where it is. I just can't get to it.", tags: ['trouble', 'funny'] },
  { text: "I didn't lose the ball, the course swallowed it.", tags: ['trouble', 'funny'] },
  { text: "The trees jumped out in front of my ball.", tags: ['trouble', 'funny'] },
  { text: "I'm not in the woods, I'm on the scenic route to the green.", tags: ['trouble', 'funny'] },

  // -- Mixed / General --
  { text: "I shot one under today. One under a tree, one under a bush, one under the water.", tags: ['trouble', 'funny'] },
  { text: "Golf is harder than baseball. At least in baseball you don't have to play your foul balls.", tags: ['funny'] },
  { text: "I have a tip that can take five shots off anyone's game. It's called an eraser.", tags: ['funny'] },
  { text: "I wish I could play my normal game. Just once.", tags: ['mental'] },
  { text: "The GPS said 150. My rangefinder said 145. I split the difference and hit it 200.", tags: ['fairway', 'equipment'] },
  { text: "I'm not slicing, I'm hitting a power fade. It's a strategy.", tags: ['tee', 'fairway', 'funny'] },
  { text: "My caddie handed me the wrong club. Oh wait, I don't have a caddie.", tags: ['funny'] },
  { text: "I'd move heaven and earth to break 100 on this course. So far I've mostly moved earth.", tags: ['tee', 'fairway', 'funny'] },

  // -- Additional excuses --
  { text: "I need some new clubs.", tags: ['equipment'] },
  { text: "I had some negative thoughts before I hit that.", tags: ['mental'] },
  { text: "Just can't feel anything today.", tags: ['conditions', 'mental'] },
  { text: "Did you see what I ate? That's why.", tags: ['funny'] },
  { text: "Some days you're not free of aches and pains, today was one of them.", tags: ['conditions'] },
  { text: "I just lost concentration on that one.", tags: ['mental'] },
  { text: "The maintenance staff put that marker in the wrong spot, not my fault.", tags: ['fairway', 'equipment'] },
  { text: "I had my mulligan on each hole.", tags: ['funny'] },
  { text: "What game am I playing?", tags: ['funny'] },
  { text: "My feet hurt from too much discount shopping.", tags: ['conditions', 'funny'] },
  { text: "At least I get to go again.", tags: ['funny'] },
  { text: "Everyone has a different strategy.", tags: ['funny'] },
  { text: "Just trying to see how quickly I can match the course record.", tags: ['funny'] },
  { text: "My dog wouldn't roll in that one.", tags: ['funny'] },
  { text: "I'm out here trying to perform miracles.", tags: ['funny'] },
  { text: "Way too much bad luck today. Can't wait to try again tomorrow.", tags: ['funny'] },
  { text: "My foot slipped.", tags: ['conditions'] },
  { text: "I saw my shadow.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "Better to have a bad round than be at work.", tags: ['funny'] },
  { text: "I'm trying new balls, still getting used to them.", tags: ['tee', 'fairway', 'equipment'] },
  { text: "New course, I'm not used to it yet.", tags: ['mental'] },
  { text: "My rangefinder lied to me.", tags: ['fairway', 'equipment'] },
  { text: "That divot wasn't there yesterday.", tags: ['fairway', 'conditions'] },
  { text: "My caddie gave me the wrong yardage. I don't have a caddie.", tags: ['fairway', 'funny'] },
  { text: "I blinked.", tags: ['tee', 'fairway', 'funny'] },
  { text: "Too much coffee this morning, hands are shaky.", tags: ['conditions'] },
  { text: "My watch buzzed right as I was about to putt.", tags: ['on_green', 'distraction'] },
  { text: "I was visualizing my next shot and forgot to hit this one.", tags: ['mental'] },
  { text: "The tee time was too early, I'm not a morning person.", tags: ['conditions', 'mental'] },
  { text: "I'm saving my good shots for the back nine.", tags: ['funny'] },
  { text: "My lucky ball is still in the water from last week.", tags: ['trouble', 'equipment'] },
  { text: "The marshal was staring at me.", tags: ['distraction'] },
  { text: "I've got new grips, still breaking them in.", tags: ['tee', 'fairway', 'equipment'] },
  { text: "The pin placement is cruel today.", tags: ['green_area', 'on_green', 'funny'] },
  { text: "My playing partner breathed too loud.", tags: ['distraction'] },
  { text: "I pulled a muscle reaching for the scorecard.", tags: ['conditions', 'funny'] },

  // -- Reddit / community excuses --
  { text: "I usually watch a bunker tips video before I play.", tags: ['green_area', 'mental'] },
  { text: "I should have done some things different.", tags: ['mental'] },
  { text: "Didn't commit to the shot.", tags: ['tee', 'fairway', 'green_area', 'mental'] },
  { text: "I looked up.", tags: ['tee', 'fairway'] },
  { text: "My arms were way ahead of my hips.", tags: ['tee', 'fairway'] },
  { text: "I had a weird hitch at the bottom of the swing.", tags: ['tee', 'fairway'] },
  { text: "That one was inside out for some reason.", tags: ['tee', 'fairway'] },
  { text: "I hit 6 inches behind the ball.", tags: ['fairway', 'green_area'] },
  { text: "The face was wide open.", tags: ['tee', 'fairway'] },
  { text: "That was a hosel rocket.", tags: ['tee', 'fairway'] },
  { text: "I should have clubbed up.", tags: ['fairway', 'equipment'] },
  { text: "I heeled that putt.", tags: ['on_green'] },
  { text: "I decelerated on that chip.", tags: ['green_area'] },
  { text: "Right line, wrong speed.", tags: ['on_green'] },
  { text: "Right speed, wrong line.", tags: ['on_green'] },
  { text: "I prefer to play in the rough anyways.", tags: ['trouble', 'funny'] },
  { text: "Mud ball.", tags: ['fairway', 'conditions'] },
  { text: "The ground was too soft today.", tags: ['conditions'] },
  { text: "Had back problems.", tags: ['conditions'] },
  { text: "Got in a car crash and nearly lost a leg.", tags: ['conditions', 'funny'] },
  { text: "Tore my Achilles.", tags: ['conditions'] },
  { text: "I never feel comfortable in shorts.", tags: ['conditions', 'funny'] },
  { text: "Blamed the pants.", tags: ['funny'] },
  { text: "Frickin' wind!", tags: ['conditions'] },
  { text: "My glutes aren't firing.", tags: ['conditions'] },
  { text: "I've never taken a lesson.", tags: ['mental'] },
  { text: "LOFT \u2014 lack of f*#!%ing talent.", tags: ['funny'] },
  { text: "I have not played in 3 years.", tags: ['mental'] },
  { text: "I sometimes forget to charge my clubs or replace the batteries between rounds.", tags: ['equipment'] },
  { text: "I didn't play as a kid.", tags: ['mental'] },
  { text: "Bad luck.", tags: ['funny'] },
  { text: "Annoying player in the foursome.", tags: ['distraction'] },
  { text: "I really have to take a dump.", tags: ['funny'] },
  { text: "18 Birdies gave me the wrong distance.", tags: ['fairway', 'equipment'] },
  { text: "According to Albert Einstein, spacetime bends. Apparently it bends sharply to the left around my driver.", tags: ['tee', 'funny'] },
  { text: "The theory of relativity means you literally could not have done any better.", tags: ['funny'] },
  { text: "There was a bee!", tags: ['tee', 'fairway', 'distraction'] },
  { text: "My shoe soles are really unevenly worn out, causing me to be thrown off balance.", tags: ['conditions', 'equipment'] },
  { text: "My phone vibrated in the backswing.", tags: ['tee', 'fairway', 'distraction'] },
  { text: "The lie was worse than it looked.", tags: ['fairway', 'conditions'] },
  { text: "I practiced too hard on the range.", tags: ['mental'] },
  { text: "I trained too hard at the gym this morning.", tags: ['conditions'] },
  { text: "Did you hear that???", tags: ['tee', 'fairway', 'distraction'] },
  { text: "My putting sucks today because my putter face is twisted from rapid temperature changes.", tags: ['on_green', 'equipment'] },
  { text: "Oh, the ball must be ruined.", tags: ['equipment'] },
  { text: "I think it's my loft.", tags: ['equipment'] },
  { text: "That was supposed to draw. I guess I left my draws at home!", tags: ['tee', 'fairway'] },
  { text: "I would have hit that better if I was better at golf.", tags: ['funny'] },
  { text: "I was in the pool!", tags: ['funny'] },
];
